### ISSUE TITLE
Cync Lights Plugin in Child Bridge Continuously Restarting and Crashing

### ISSUE THREAD

**Issue by dmoore0157** [davidashman/homebridge-cync-lights#14]
**Describe Your Problem:**
I initially faced an issue where the Cync Lights plugin caused my entire Homebridge server to crash repeatedly. To resolve this, I configured the plugin to run in a child bridge, which stabilized my Homebridge server. However, now the Cync Lights plugin within the child bridge is stuck in a continuous loop of starting and stopping. It appears that an error with one of the switches may be causing the bridge to crash and restart repeatedly. I need assistance to identify and fix the underlying issue causing these crashes.

**Logs:**
[7/29/2024, 8:52:01 AM] [Cync Lights] Discovering homes...
[7/29/2024, 8:52:01 AM] [Cync Lights] Checking access token expiration
[7/29/2024, 8:52:01 AM] [Cync Lights] Updating access token...
[7/29/2024, 8:52:01 AM] [Cync Lights] Payload: {"refresh_token":"<REDACTED>"}
[7/29/2024, 8:52:01 AM] [Cync Lights] Got packet header with type 1, header 1800000002, length 2
[7/29/2024, 8:52:01 AM] [Cync Lights] Cync server connected.
[7/29/2024, 8:52:01 AM] [Cync Lights] Processing queue of 0 packets.
[7/29/2024, 8:52:01 AM] [Cync Lights] New access token expires in undefined seconds.
[7/29/2024, 8:52:01 AM] [Cync Lights] Expiration date set to Invalid Date.
[7/29/2024, 8:52:01 AM] [Cync Lights] Received home response: [{"subscribe_date":"2024-07-29T01:42:28.156Z","is_active":true,"role":1,"last_login":"2024-07-28T20:16:51.634Z","firmware_mod":"1","active_code":"<REDACTED>","active_date":"2021-02-06T18:19:17.600Z","groups":"","mcu_version":1,"firmware_version":15632,"source":2,"mac":"<REDACTED>","mcu_mod":"1","product_id":"<REDACTED>","access_key":777,"authority":"RW","name":"","authorize_code":"<REDACTED>","id":705015461,"is_online":true},...]
[7/29/2024, 8:52:01 AM] [Cync Lights] Loading home information from <URL REDACTED>
[7/29/2024, 8:52:01 AM] [Cync Lights] Received device response: {"bulbsArray":[{"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}]}
[7/29/2024, 8:52:01 AM] [Cync Lights] Registering device: {"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}
[7/29/2024, 8:52:01 AM] [Cync Lights] Child bridge process ended
[7/29/2024, 8:52:01 AM] [Cync Lights] Process Ended. Code: 1, Signal: null
[7/29/2024, 8:52:08 AM] [Cync Lights] Restarting Process...
[7/29/2024, 8:52:09 AM] [Cync Lights] Launched child bridge with PID 88397
[7/29/2024, 8:52:09 AM] Registering platform 'homebridge-cync-lights.CyncLights'
[7/29/2024, 8:52:09 AM] [Cync Lights] Loaded homebridge-cync-lights v1.8.10 child bridge successfully
[7/29/2024, 8:52:09 AM] Loaded 1 cached accessories from cachedAccessories.<REDACTED>.
[7/29/2024, 8:52:09 AM] [Cync Lights] Identity file: /var/lib/homebridge/cync.json
[7/29/2024, 8:52:09 AM] [Cync Lights] Returning contents of /var/lib/homebridge/cync.json
[7/29/2024, 8:52:09 AM] [Cync Lights] Identity: {"access_token":"<REDACTED>","refresh_token":"<REDACTED>","user_id":<REDACTED>,"expire_in":604800,"authorize":"<REDACTED>"}
[7/29/2024, 8:52:09 AM] [Cync Lights] Loading accessory from cache: Vanity light
[7/29/2024, 8:52:09 AM] [Cync Lights] Connecting to Cync server...
[7/29/2024, 8:52:09 AM] [Cync Lights] Authenticating with Cync server...
[7/29/2024, 8:52:09 AM] [Cync Lights] Authenticating with packet: <REDACTED>
[7/29/2024, 8:52:09 AM] Homebridge v1.8.4 (HAP v0.12.2) (Cync Lights) is running on port 36196.
[7/29/2024, 8:52:09 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> <URL REDACTED>

[7/29/2024, 8:52:09 AM] [Cync Lights] Discovering homes...
[7/29/2024, 8:52:09 AM] [Cync Lights] Checking access token expiration
[7/29/2024, 8:52:09 AM] [Cync Lights] Updating access token...
[7/29/2024, 8:52:09 AM] [Cync Lights] Payload: {"refresh_token":"<REDACTED>"}
[7/29/2024, 8:52:09 AM] [Cync Lights] Got packet header with type 1, header 1800000002, length 2
[7/29/2024, 8:52:09 AM] [Cync Lights] Cync server connected.
[7/29/2024, 8:52:09 AM] [Cync Lights] Processing queue of 0 packets.
[7/29/2024, 8:52:09 AM] [Cync Lights] New access token expires in undefined seconds.
[7/29/2024, 8:52:09 AM] [Cync Lights] Expiration date set to Invalid Date.
[7/29/2024, 8:52:09 AM] [Cync Lights] Received home response: [{"subscribe_date":"2024-07-29T01:42:28.156Z","is_active":true,"role":1,"last_login":"2024-07-28T20:16:51.634Z","firmware_mod":"1","active_code":"<REDACTED>","active_date":"2021-02-06T18:19:17.600Z","groups":"","mcu_version":1,"firmware_version":15632,"source":2,"mac":"<REDACTED>","mcu_mod":"1","product_id":"<REDACTED>","access_key":777,"authority":"RW","name":"","authorize_code":"<REDACTED>","id":705015461,"is_online":true},...]
[7/29/2024, 8:52:09 AM] [Cync Lights] Loading home information from <URL REDACTED>
[7/29/2024, 8:52:09 AM] [Cync Lights] Received device response: {"bulbsArray":[{"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}]}
[7/29/2024, 8:52:09 AM] [Cync Lights] Registering device: {"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}
[7/29/2024, 8:52:09 AM] [Cync Lights] Child bridge process ended
[7/29/2024, 8:52:09 AM] [Cync Lights] Process Ended. Code: 1, Signal: null
[7/29/2024, 8:52:16 AM] [Cync Lights] Restarting Process...
[7/29/2024, 8:52:17 AM] [Cync Lights] Launched child bridge with PID 88411
[7/29/2024, 8:52:17 AM] Registering platform 'homebridge-cync-lights.CyncLights'
[7/29/2024, 8:52:17 AM] [Cync Lights] Loaded homebridge-cync-lights v1.8.10 child bridge successfully
[7/29/2024, 8:52:17 AM] Loaded 1 cached accessories from cachedAccessories.<REDACTED>.
[7/29/2024, 8:52:17 AM] [Cync Lights] Identity file: /var/lib/homebridge/cync.json
[7/29/2024, 8:52:17 AM] [Cync Lights] Returning contents of /var/lib/homebridge/cync.json
[7/29/2024, 8:52:17 AM] [Cync Lights] Identity: {"access_token":"<REDACTED>","refresh_token":"<REDACTED>","user_id":<REDACTED>,"expire_in":604800,"authorize":"<REDACTED>"}
[7/29/2024, 8:52:17 AM] [Cync Lights] Loading accessory from cache: Vanity light
[7/29/2024, 8:52:17 AM] [Cync Lights] Connecting to Cync server...
[7/29/2024, 8:52:17 AM] [Cync Lights] Authenticating with Cync server...
[7/29/2024, 8:52:17 AM] [Cync Lights] Authenticating with packet: <REDACTED>
[7/29/2024, 8:52:17 AM] Homebridge v1.8.4 (HAP v0.12.2) (Cync Lights) is running on port 36196.
[7/29/2024, 8:52:17 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> <URL REDACTED>

[7/29/2024, 8:52:17 AM] [Cync Lights] Discovering homes...
[7/29/2024, 8:52:17 AM] [Cync Lights] Checking access token expiration
[7/29/2024, 8:52:17 AM] [Cync Lights] Updating access token...
[7/29/2024, 8:52:17 AM] [Cync Lights] Payload: {"refresh_token":"<REDACTED>"}
[7/29/2024, 8:52:17 AM] [Cync Lights] Got packet header with type 1, header 1800000002, length 2
[7/29/2024, 8:52:17 AM] [Cync Lights] Cync server connected.
[7/29/2024, 8:52:17 AM] [Cync Lights] Processing queue of 0 packets.
[7/29/2024, 8:52:17 AM] [Cync Lights] New access token expires in undefined seconds.
[7/29/2024, 8:52:17 AM] [Cync Lights] Expiration date set to Invalid Date.
[7/29/2024, 8:52:17 AM] [Cync Lights] Received home response: [{"subscribe_date":"2024-07-29T01:42:28.156Z","is_active":true,"role":1,"last_login":"2024-07-28T20:16:51.634Z","firmware_mod":"1","active_code":"<REDACTED>","active_date":"2021-02-06T18:19:17.600Z","groups":"","mcu_version":1,"firmware_version":15632,"source":2,"mac":"<REDACTED>","mcu_mod":"1","product_id":"<REDACTED>","access_key":777,"authority":"RW","name":"","authorize_code":"<REDACTED>","id":705015461,"is_online":true},...]
[7/29/2024, 8:52:17 AM] [Cync Lights] Loading home information from <URL REDACTED>
[7/29/2024, 8:52:17 AM] [Cync Lights] Received device response: {"bulbsArray":[{"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}]}
[7/29/2024, 8:52:17 AM] [Cync Lights] Registering device: {"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}
[7/29/2024, 8:52:17 AM] [Cync Lights] Child bridge process ended
[7/29/2024, 8:52:17 AM] [Cync Lights] Process Ended. Code: 1, Signal: null
[7/29/2024, 8:52:24 AM] [Cync Lights] Restarting Process...
[7/29/2024, 8:52:25 AM] [Cync Lights] Launched child bridge with PID 88425
[7/29/2024, 8:52:25 AM] Registering platform 'homebridge-cync-lights.CyncLights'
[7/29/2024, 8:52:25 AM] [Cync Lights] Loaded homebridge-cync-lights v1.8.10 child bridge successfully
[7/29/2024, 8:52:25 AM] Loaded 1 cached accessories from cachedAccessories.<REDACTED>.
[7/29/2024, 8:52:25 AM] [Cync Lights] Identity file: /var/lib/homebridge/cync.json
[7/29/2024, 8:52:25 AM] [Cync Lights] Returning contents of /var/lib/homebridge/cync.json
[7/29/2024, 8:52:25 AM] [Cync Lights] Identity: {"access_token":"<REDACTED>","refresh_token":"<REDACTED>","user_id":<REDACTED>,"expire_in":604800,"authorize":"<REDACTED>"}
[7/29/2024, 8:52:25 AM] [Cync Lights] Loading accessory from cache: Vanity light
[7/29/2024, 8:52:25 AM] [Cync Lights] Connecting to Cync server...
[7/29/2024, 8:52:25 AM] [Cync Lights] Authenticating with Cync server...
[7/29/2024, 8:52:25 AM] [Cync Lights] Authenticating with packet: <REDACTED>
[7/29/2024, 8:52:25 AM] Homebridge v1.8.4 (HAP v0.12.2) (Cync Lights) is running on port 36196.
[7/29/2024, 8:52:25 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> <URL REDACTED>

[7/29/2024, 8:52:25 AM] [Cync Lights] Discovering homes...
[7/29/2024, 8:52:25 AM] [Cync Lights] Checking access token expiration
[7/29/2024, 8:52:25 AM] [Cync Lights] Updating access token...
[7/29/2024, 8:52:25 AM] [Cync Lights] Payload: {"refresh_token":"<REDACTED>"}
[7/29/2024, 8:52:25 AM] [Cync Lights] Got packet header with type 1, header 1800000002, length 2
[7/29/2024, 8:52:25 AM] [Cync Lights] Cync server connected.
[7/29/2024, 8:52:25 AM] [Cync Lights] Processing queue of 0 packets.
[7/29/2024, 8:52:25 AM] [Cync Lights] New access token expires in undefined seconds.
[7/29/2024, 8:52:25 AM] [Cync Lights] Expiration date set to Invalid Date.
[7/29/2024, 8:52:25 AM] [Cync Lights] Received home response: [{"subscribe_date":"2024-07-29T01:42:28.156Z","is_active":true,"role":1,"last_login":"2024-07-28T20:16:51.634Z","firmware_mod":"1","active_code":"<REDACTED>","active_date":"2021-02-06T18:19:17.600Z","groups":"","mcu_version":1,"firmware_version":15632,"source":2,"mac":"<REDACTED>","mcu_mod":"1","product_id":"<REDACTED>","access_key":777,"authority":"RW","name":"","authorize_code":"<REDACTED>","id":705015461,"is_online":true},...]
[7/29/2024, 8:52:25 AM] [Cync Lights] Loading home information from <URL REDACTED>
[7/29/2024, 8:52:25 AM] [Cync Lights] Received device response: {"bulbsArray":[{"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}]}
[7/29/2024, 8:52:25 AM] [Cync Lights] Registering device: {"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}
[7/29/2024, 8:52:25 AM] [Cync Lights] Child bridge process ended
[7/29/2024, 8:52:25 AM] [Cync Lights] Process Ended. Code: 1, Signal: null
[7/29/2024, 8:52:32 AM] [Cync Lights] Restarting Process...
[7/29/2024, 8:52:33 AM] [Cync Lights] Launched child bridge with PID 88439
[7/29/2024, 8:52:33 AM] Registering platform 'homebridge-cync-lights.CyncLights'
[7/29/2024, 8:52:33 AM] [Cync Lights] Loaded homebridge-cync-lights v1.8.10 child bridge successfully
[7/29/2024, 8:52:33 AM] Loaded 1 cached accessories from cachedAccessories.<REDACTED>.
[7/29/2024, 8:52:33 AM] [Cync Lights] Identity file: /var/lib/homebridge/cync.json
[7/29/2024, 8:52:33 AM] [Cync Lights] Returning contents of /var/lib/homebridge/cync.json
[7/29/2024, 8:52:33 AM] [Cync Lights] Identity: {"access_token":"<REDACTED>","refresh_token":"<REDACTED>","user_id":<REDACTED>,"expire_in":604800,"authorize":"<REDACTED>"}
[7/29/2024, 8:52:33 AM] [Cync Lights] Loading accessory from cache: Vanity light
[7/29/2024, 8:52:33 AM] [Cync Lights] Connecting to Cync server...
[7/29/2024, 8:52:33 AM] [Cync Lights] Authenticating with Cync server...
[7/29/2024, 8:52:33 AM] [Cync Lights] Authenticating with packet: <REDACTED>
[7/29/2024, 8:52:33 AM] Homebridge v1.8.4 (HAP v0.12.2) (Cync Lights) is running on port 36196.
[7/29/2024, 8:52:33 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> <URL REDACTED>

[7/29/2024, 8:52:33 AM] [Cync Lights] Discovering homes...
[7/29/2024, 8:52:33 AM] [Cync Lights] Checking access token expiration
[7/29/2024, 8:52:33 AM] [Cync Lights] Updating access token...
[7/29/2024, 8:52:33 AM] [Cync Lights] Payload: {"refresh_token":"<REDACTED>"}
[7/29/2024, 8:52:33 AM] [Cync Lights] Got packet header with type 1, header 1800000002, length 2
[7/29/2024, 8:52:33 AM] [Cync Lights] Cync server connected.
[7/29/2024, 8:52:33 AM] [Cync Lights] Processing queue of 0 packets.
[7/29/2024, 8:52:33 AM] [Cync Lights] New access token expires in undefined seconds.
[7/29/2024, 8:52:33 AM] [Cync Lights] Expiration date set to Invalid Date.
[7/29/2024, 8:52:33 AM] [Cync Lights] Received home response: [{"subscribe_date":"2024-07-29T01:42:28.156Z","is_active":true,"role":1,"last_login":"2024-07-28T20:16:51.634Z","firmware_mod":"1","active_code":"<REDACTED>","active_date":"2021-02-06T18:19:17.600Z","groups":"","mcu_version":1,"firmware_version":15632,"source":2,"mac":"<REDACTED>","mcu_mod":"1","product_id":"<REDACTED>","access_key":777,"authority":"RW","name":"","authorize_code":"<REDACTED>","id":705015461,"is_online":true},...]
[7/29/2024, 8:52:33 AM] [Cync Lights] Loading home information from <URL REDACTED>
[7/29/2024, 8:52:33 AM] [Cync Lights] Received device response: {"bulbsArray":[{"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}]}
[7/29/2024, 8:52:33 AM] [Cync Lights] Registering device: {"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}
[7/29/2024, 8:52:33 AM] [Cync Lights] Child bridge process ended
[7/29/2024, 8:52:33 AM] [Cync Lights] Process Ended. Code: 1, Signal: null
[7/29/2024, 8:52:41 AM] [Cync Lights] Restarting Process...
[7/29/2024, 8:52:41 AM] [Cync Lights] Launched child bridge with PID 88453
[7/29/2024, 8:52:41 AM] Registering platform 'homebridge-cync-lights.CyncLights'
[7/29/2024, 8:52:41 AM] [Cync Lights] Loaded homebridge-cync-lights v1.8.10 child bridge successfully
[7/29/2024, 8:52:41 AM] Loaded 1 cached accessories from cachedAccessories.<REDACTED>.
[7/29/2024, 8:52:41 AM] [Cync Lights] Identity file: /var/lib/homebridge/cync.json
[7/29/2024, 8:52:41 AM] [Cync Lights] Returning contents of /var/lib/homebridge/cync.json
[7/29/2024, 8:52:41 AM] [Cync Lights] Identity: {"access_token":"<REDACTED>","refresh_token":"<REDACTED>","user_id":<REDACTED>,"expire_in":604800,"authorize":"<REDACTED>"}
[7/29/2024, 8:52:41 AM] [Cync Lights] Loading accessory from cache: Vanity light
[7/29/2024, 8:52:41 AM] [Cync Lights] Connecting to Cync server...
[7/29/2024, 8:52:41 AM] [Cync Lights] Authenticating with Cync server...
[7/29/2024, 8:52:41 AM] [Cync Lights] Authenticating with packet: <REDACTED>
[7/29/2024, 8:52:41 AM] Homebridge v1.8.4 (HAP v0.12.2) (Cync Lights) is running on port 36196.
[7/29/2024, 8:52:41 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> <URL REDACTED>

[7/29/2024, 8:52:41 AM] [Cync Lights] Discovering homes...
[7/29/2024, 8:52:41 AM] [Cync Lights] Checking access token expiration
[7/29/2024, 8:52:41 AM] [Cync Lights] Updating access token...
[7/29/2024, 8:52:41 AM] [Cync Lights] Payload: {"refresh_token":"<REDACTED>"}
[7/29/2024, 8:52:41 AM] [Cync Lights] Got packet header with type 1, header 1800000002, length 2
[7/29/2024, 8:52:41 AM] [Cync Lights] Cync server connected.
[7/29/2024, 8:52:41 AM] [Cync Lights] Processing queue of 0 packets.
[7/29/2024, 8:52:41 AM] [Cync Lights] New access token expires in undefined seconds.
[7/29/2024, 8:52:41 AM] [Cync Lights] Expiration date set to Invalid Date.
[7/29/2024, 8:52:41 AM] [Cync Lights] Received home response: [{"subscribe_date":"2024-07-29T01:42:28.156Z","is_active":true,"role":1,"last_login":"2024-07-28T20:16:51.634Z","firmware_mod":"1","active_code":"<REDACTED>","active_date":"2021-02-06T18:19:17.600Z","groups":"","mcu_version":1,"firmware_version":15632,"source":2,"mac":"<REDACTED>","mcu_mod":"1","product_id":"<REDACTED>","access_key":777,"authority":"RW","name":"","authorize_code":"<REDACTED>","id":705015461,"is_online":true},...]
[7/29/2024, 8:52:41 AM] [Cync Lights] Loading home information from <URL REDACTED>
[7/29/2024, 8:52:41 AM] [Cync Lights] Received device response: {"bulbsArray":[{"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}]}
[7/29/2024, 8:52:41 AM] [Cync Lights] Registering device: {"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}
[7/29/2024, 8:52:41 AM] [Cync Lights] Child bridge process ended
[7/29/2024, 8:52:41 AM] [Cync Lights] Process Ended. Code: 1, Signal: null

```
Show the Homebridge logs here, remove any sensitive information.
[7/29/2024, 8:52:58 AM] [Cync Lights] Received home response: [{"subscribe_date":"2024-07-29T01:42:28.156Z","is_active":true,"role":1,"last_login":"2024-07-28T20:16:51.634Z","firmware_mod":"1","active_code":"<REDACTED>","active_date":"2021-02-06T18:19:17.600Z","groups":"","mcu_version":1,"firmware_version":15632,"source":2,"mac":"<REDACTED>","mcu_mod":"1","product_id":"<REDACTED>","access_key":777,"authority":"RW","name":"","authorize_code":"<REDACTED>","id":705015461,"is_online":true},{"subscribe_date":"2024-07-29T01:42:28.164Z","is_active":true,"role":1,"last_login":"2024-07-27T11:47:42.44Z","firmware_mod":"1","active_code":"<REDACTED>","active_date":"2020-09-13T18:00:36.789Z","groups":"","mcu_version":1,"firmware_version":15632,"source":2,"mac":"<REDACTED>","mcu_mod":"1","product_id":"<REDACTED>","access_key":777,"authority":"RW","name":"","authorize_code":"<REDACTED>","id":705013860,"is_online":true},{"subscribe_date":"2024-07-29T01:42:28.168Z","is_active":true,"role":1,"last_login":"2024-07-26T19:38:29.819Z","firmware_mod":"1","active_code":"<REDACTED>","active_date":"2020-09-13T17:21:35.57Z","groups":"","mcu_version":1,"firmware_version":15632,"source":2,"mac":"<REDACTED>","mcu_mod":"1","product_id":"<REDACTED>","access_key":777,"authority":"RW","name":"Ktchen 1","authorize_code":"<REDACTED>","id":705015025,"is_online":true},{"subscribe_date":"2024-07-29T01:42:28.177Z","is_active":true,"role":1,"last_login":"","active_code":"<REDACTED>","active_date":"2020-09-13T17:18:07.197Z","groups":"","mcu_version":0,"firmware_version":0,"source":2,"mac":"<REDACTED>","product_id":"<REDACTED>","access_key":<REDACTED>,"authority":"RW","name":"Home","authorize_code":"<REDACTED>","id":595437959,"is_online":false},{"subscribe_date":"2024-07-29T01:42:28.182Z","is_active":true,"role":1,"last_login":"2024-07-28T19:46:37.764Z","firmware_mod":"1","active_code":"<REDACTED>","active_date":"2021-02-06T20:16:19.577Z","groups":"","mcu_version":1,"firmware_version":15632,"source":2,"mac":"<REDACTED>","mcu_mod":"1","product_id":"<REDACTED>","access_key":777,"authority":"RW","name":"","authorize_code":"<REDACTED>","id":705019001,"is_online":true}]
[7/29/2024, 8:52:58 AM] [Cync Lights] Loading home information from <URL REDACTED>
[7/29/2024, 8:52:58 AM] [Cync Lights] Received device response: {"bulbsArray":[{"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}]}
[7/29/2024, 8:52:58 AM] [Cync Lights] Registering device: {"deviceType":59,"switchID":705015461013,"displayName":"Vanity light","deviceID":705015461013}
[7/29/2024, 8:52:58 AM] [homebridge-cync-lights] This plugin generated a warning from the characteristic 'Firmware Revision': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.
[7/29/2024, 8:52:58 AM] [homebridge-cync-lights] This plugin generated a warning from the characteristic 'Serial Number': characteristic value expected string and received undefined. See https://homebridge.io/w/JtMGR for more info.
RangeError: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received 705_015_461_013
    at checkInt (node:internal/buffer:74:11)
    at writeU_Int32BE (node:internal/buffer:804:3)
    at Buffer.writeUInt32BE (node:internal/buffer:817:10)
    at CyncHub.updateConection (file:///homebridge/node_modules/homebridge-cync-lights/src/hub.ts:227:10)
    at CyncHub.registerDevice (file:///homebridge/node_modules/homebridge-cync-lights/src/hub.ts:318:12)
    at file:///homebridge/node_modules/homebridge-cync-lights/src/platform.ts:86:16
    at CyncApi.forEachDevice (file:///homebridge/node_modules/homebridge-cync-lights/src/api.ts:143:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at CyncLightsPlatform.discoverDevices (file:///homebridge/node_modules/homebridge-cync-lights/src/platform.ts:69:5)
[7/29/2024, 8:52:58 AM] [Cync Lights] Child bridge process ended
[7/29/2024, 8:52:58 AM] [Cync Lights] Process Ended. Code: 1, Signal: null
[7/29/2024, 8:53:05 AM] [Cync Lights] Restarting Process...
[7/29/2024, 8:53:05 AM] [Cync Lights] Launched child bridge with PID 88492
[7/29/2024, 8:53:05 AM] Registering platform 'homebridge-cync-lights.CyncLights'
[7/29/2024, 8:53:05 AM] [Cync Lights] Loaded homebridge-cync-lights v1.8.10 child bridge successfully
[7/29/2024, 8:53:05 AM] Loaded 1 cached accessories from cachedAccessories.<REDACTED>.
[7/29/2024, 8:53:05 AM] [Cync Lights] Identity file: /var/lib/homebridge/cync.json
[7/29/2024, 8:53:05 AM] [Cync Lights] Returning contents of /var/lib/homebridge/cync.json
[7/29/2024, 8:53:05 AM] [Cync Lights] Identity: {"access_token":"<REDACTED>","refresh_token":"<REDACTED>","user_id":<REDACTED>,"expire_in":604800,"authorize":"<REDACTED>"}
[7/29/2024, 8:53:05 AM] [Cync Lights] Loading accessory from cache: Vanity light
[7/29/2024, 8:53:05 AM] [Cync Lights] Connecting to Cync server...
[7/29/2024, 8:53:05 AM] [Cync Lights] Authenticating with Cync server...
[7/29/2024, 8:53:05 AM] [Cync Lights] Authenticating with packet: <REDACTED>
[7/29/2024, 8:53:05 AM] Homebridge v1.8.4 (HAP v0.12.2) (Cync Lights) is running on port 36196.


**Plugin Config:**
{
    "platform": "CyncLights",
    "name": "Cync Lights",
    "emailAddress": "redacted",
    "refreshToken": "redacted",
    "userID": redacted,
    "authorize": "redacted",
    "_bridge": {
        "username": "redacted",
        "port": 30196
    }
}
```json
Show your Homebridge config.json here, remove any sensitive information.
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "<REDACTED>",
        "port": 51083,
        "pin": "<REDACTED>"
    },
    "description": "Home Smart Home",
    "platforms": [
        {
            "name": "Config-HB01092020",
            "port": 8581,
            "auth": "form",
            "theme": "dark-mode-blue-grey",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "name": "TplinkSmarthome",
            "addCustomCharacteristics": true,
            "broadcast": "ip address",
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome"
        },
        {
            "name": "TuyaWebPlatform",
            "options": {
                "username": "<REDACTED>",
                "password": "<REDACTED>",
                "countryCode": "1",
                "platform": "smart_life"
            },
            "defaults": [
                {
                    "device_type": "form"
                }
            ],
            "scenes": false,
            "platform": "TuyaWebPlatform"
        },
        {
            "refreshToken": "<REDACTED>",
            "unbridgeCameras": false,
            "avoidSnapshotBatteryDrain": true,
            "_bridge": {
                "username": "<REDACTED>",
                "port": 30990
            },
            "platform": "Ring"
        },
        {
            "name": "Nest",
            "googleAuth": {
                "issueToken": "<REDACTED>",
                "cookies": "<REDACTED>",
                "apiKey": "<REDACTED>"
            },
            "platform": "Nest"
        },
        {
            "name": "SwitchBot",
            "credentials": {
                "token": "<REDACTED>",
                "secret": "<REDACTED>",
                "notice": "Keep your Token & Secret a secret!"
            },
            "options": {
                "BLE": true
            },
            "platform": "SwitchBot"
        },
        {
            "platform": "CyncLights",
            "name": "Cync Lights",
            "emailAddress": "<REDACTED>",
            "refreshToken": "<REDACTED>",
            "userID": "<REDACTED>",
            "authorize": "<REDACTED>",
            "_bridge": {
                "username": "<REDACTED>",
                "port": 30196
            }
        }
    ],
    "accessories": [],
    "disabledPlugins": [
        "homebridge-yi-camera"
    ]
}

**Screenshots:**

**Environment:**

* **Plugin Version**:  Homebridge Cync Lights V 1.8.10
* **Homebridge Version**:  Hombridge 1.8.4
* **Node.js Version**:  v20.15.0
* **NPM Version**: 8.5.5
* **Operating System**:  Ubuntu Jammy (22.04.4 LTS) running in Docker

**Comment by tomiy1** [comment]
I am now observing the same constant crashing. Is anyone looking into it? Thanks!
